mkdir -p ~/bin;
mkdir -p ~/npm;
mkdir -p ~/work/src;
mkdir -p ~/.config;
mkdir -p ~/.config/Code/User;

rm -rf ~/.gitconfig;
rm -rf ~/.gitignore_global;
rm -rf ~/.userrc;
rm -rf ~/.tmux.conf;
rm -rf ~/.npmrc;
rm -rf ~/.vimrc;
rm -rf ~/.xinitrc;
rm -rf ~/.config/Code/User/*;
rm -rf ~/.config/xfce4;
rm -rf ~/.config/xubuntu;
rm -rf ~/.config/gtk-2.0;
rm -rf ~/.config/gtk-3.0;

cp .gitconfig ~/.gitconfig;
cp .gitignore_global ~/.gitignore_global;
cp .userrc ~/.userrc;
cp .tmux.conf ~/.tmux.conf;
cp .npmrc ~/.npmrc;
cp .vimrc ~/.vimrc;
cp .Xdefaults ~/.Xdefaults;
cp -rf Code/User/* ~/.config/Code/User/;
cp -rf vscode/* ~/.vscode/;
cp -rf xfce4 ~/.config/xfce4;
cp -rf xubuntu ~/.config/xubuntu;
cp -rf gtk-2.0 ~/.config/gtk-2.0;
cp -rf gtk-3.0 ~/.config/gtk-3.0;
